Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6114"
  end
end
# sudo DEBIAN_FRONTEND=noninteractive apt install -y <packages>
