"""add language to posts

Revision ID: 4ec952f599f0
Revises: ccf61b59d4fd
Create Date: 2026-06-13 13:43:35.450314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec952f599f0'
down_revision = 'ccf61b59d4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        # set a server_default so SQLite can populate existing rows when
        # adding a NOT NULL column
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=False,
                                      server_default=sa.text("'en'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
