"""add remaining missing tables and columns

Revision ID: 5448acb9734f
Revises: c9f1a4b7e0d3
Create Date: 2026-07-21 10:04:21.850117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5448acb9734f'
down_revision = 'c9f1a4b7e0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('equipment_type', sa.String(length=20), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('attack_bonus', sa.Integer(), nullable=False),
    sa.Column('defense_bonus', sa.Integer(), nullable=False),
    sa.Column('hp_bonus', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('token_cost', sa.Integer(), nullable=False),
    sa.Column('strength_bonus', sa.Integer(), nullable=False),
    sa.Column('speed_bonus', sa.Integer(), nullable=False),
    sa.Column('magic_bonus', sa.Integer(), nullable=False),
    sa.Column('recovery_bonus', sa.Integer(), nullable=False),
    sa.Column('stamina_bonus', sa.Integer(), nullable=False),
    sa.Column('luck_bonus', sa.Integer(), nullable=False),
    sa.Column('durability_drain', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_sign_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tokens_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_sign_in', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_sign_in_user_id'), ['user_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('player_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('total_floors_cleared', sa.Integer(), nullable=False),
    sa.Column('enemies_defeated', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('magic', sa.Integer(), nullable=False),
    sa.Column('recovery', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('luck', sa.Integer(), nullable=False),
    sa.Column('weapon_durability', sa.Integer(), nullable=False),
    sa.Column('free_points', sa.Integer(), nullable=False),
    sa.Column('is_dead', sa.Boolean(), nullable=False),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_character_user_id'), ['user_id'], unique=True)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_timestamp'), ['timestamp'], unique=False)

    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_like')
    )
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_like_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_like_user_id'), ['user_id'], unique=False)

    op.create_table('player_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player_character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_inventory_player_id'), ['player_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('player_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_inventory_player_id'))

    op.drop_table('player_inventory')
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_like_user_id'))
        batch_op.drop_index(batch_op.f('ix_like_post_id'))

    op.drop_table('like')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_timestamp'))

    op.drop_table('comment')
    with op.batch_alter_table('player_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_character_user_id'))

    op.drop_table('player_character')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    op.drop_table('message')
    with op.batch_alter_table('daily_sign_in', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_sign_in_user_id'))

    op.drop_table('daily_sign_in')
    op.drop_table('equipment')
    # ### end Alembic commands ###
