"""add user_session table and user-agent fields

Revision ID: a7c3f8e21d6b
Revises: ee17402807dc
Create Date: 2026-07-18 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c3f8e21d6b'
down_revision = 'ee17402807dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('accept_language', sa.String(length=120), nullable=True),
    sa.Column('ua_bot_flag', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('ua_bot_reason', sa.String(length=120), nullable=True),
    sa.Column('ai_probability', sa.Float(), nullable=True),
    sa.Column('ai_prediction', sa.String(length=10), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_session_uid'), ['session_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_session_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tracked_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_uid', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_tracked_action_session_uid'), ['session_uid'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_user_agent', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_accept_language', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_accept_language')
        batch_op.drop_column('last_user_agent')

    with op.batch_alter_table('tracked_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_action_session_uid'))
        batch_op.drop_column('session_uid')

    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_session_session_uid'))

    op.drop_table('user_session')
    # ### end Alembic commands ###
