"""add last_message_at and tokens to user

Revision ID: c9f1a4b7e0d3
Revises: a7c3f8e21d6b
Create Date: 2026-07-21 09:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f1a4b7e0d3'
down_revision = 'a7c3f8e21d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tokens', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tokens')
        batch_op.drop_column('last_message_at')
    # ### end Alembic commands ###
