"""add is_admin flag to user

Revision ID: ee17402807dc
Revises: 4ec952f599f0
Create Date: 2026-06-28 03:01:33.867991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee17402807dc'
down_revision = '4ec952f599f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracked_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_action_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_action_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('terms_accepted_at')

    with op.batch_alter_table('tracked_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_action_user_id'))
        batch_op.drop_index(batch_op.f('ix_tracked_action_timestamp'))

    op.drop_table('tracked_action')
    # ### end Alembic commands ###
